{
 "title": "S3 Backups",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "folder", "query": "label_values(folder)" }
  ]
 },
 "panels": [
  {
   "title": "Backup Files #",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "s3_file_count", "legendFormat": "{{folder}}" }
   ]
  },
  {
   "title": "Latest Backup Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(folder) (s3_latest_file_size)",
     "legendFormat": "{{folder}}"
    }
   ]
  },
  { "title": "Current stat for ${folder}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "folder" },
  {
   "title": "Latest File Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 9 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    { "expr": "max(s3_latest_file_timestamp)" }
   ]
  },
  {
   "title": "Oldest File Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 9 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    { "expr": "max(s3_oldest_file_timestamp)" }
   ]
  },
  {
   "title": "Latest File Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 10, "y": 9 },
   "format": "decbytes",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(s3_latest_file_size{folder=\"$folder\"})  "
    }
   ]
  },
  { "title": "Current stat for ${folder}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Latest File Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 12 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    { "expr": "max(s3_latest_file_timestamp)" }
   ]
  },
  {
   "title": "Oldest File Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 12 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    { "expr": "max(s3_oldest_file_timestamp)" }
   ]
  },
  {
   "title": "Latest File Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 10, "y": 12 },
   "format": "decbytes",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(s3_latest_file_size{folder=\"$folder\"})  "
    }
   ]
  }
 ]
}