{
 "title": "Portspesialisten: System and Docker Stats (6803)",
 "description": "System And Docker Monitoring Template",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(node_uname_info,instance)"
   },
   {
    "name": "Image",
    "query": "label_values(container_cpu_system_seconds_total{image!=\"\"},image)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Overview $Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Swap usage $Node",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100*(sum(node_memory_SwapTotal_bytes{instance=~\"^($Node).*\"}) - sum(node_memory_SwapFree_bytes{instance=~\"^($Node).*\"}) ) / sum(node_memory_SwapTotal_bytes{instance=~\"^($Node).*\"})",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "Memory usage $Node",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{instance=~\"^($Node).*\"}) - sum(node_memory_MemFree_bytes{instance=~\"^($Node).*\"}+node_memory_Buffers_bytes{instance=~\"^($Node).*\"}+node_memory_Cached_bytes{instance=~\"^($Node).*\"}) ) / sum(node_memory_MemTotal_bytes{instance=~\"^($Node).*\"}) * 100"
    }
   ]
  },
  {
   "title": "Filesystem usage $Node",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - 100 * sum(node_filesystem_free_bytes{instance=~\"^($Node).*\"}) / sum(node_filesystem_size_bytes{instance=~\"^($Node).*\"}) "
    }
   ]
  },
  {
   "title": "Nodes Information",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "node_boot_time_seconds{instance=~\"^($Node).*\"}"
    }
   ]
  },
  {
   "title": "CPU usage $Node",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg  (irate(node_cpu_seconds_total{mode=\"idle\",instance=~\"^($Node).*\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Swap usage $Node",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_SwapTotal_bytes{instance=~\"^($Node).*\"})  ",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "Memory usage $Node",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"^($Node).*\"})"
    }
   ]
  },
  {
   "title": "Filesystem usage $Node",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"^($Node).*\"})"
    }
   ]
  },
  { "title": "System $Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Load Average 1m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * sum by (instance) (node_load1)"
    }
   ]
  },
  {
   "title": "Load Average 5m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * sum by (instance) (node_load5)"
    }
   ]
  },
  {
   "title": "Host Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,device) (rate(node_network_receive_bytes_total{device!~\"^(eth2|eth1|lo|br|docker|veth|flannel|virbr).*\",instance=~\"^($Node).*\"}[1m]))",
     "legendFormat": "-> {{ instance}} {{ device }}"
    }
   ]
  },
  {
   "title": "Host disk usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - 100 * ( sum by (instance) (node_filesystem_free_bytes{instance=~\"^($Node).*\"}) /sum  by (instance) (node_filesystem_size_bytes{instance=~\"^($Node).*\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Host cpu usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\",instance=~\"^($Node).*\"}[1m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Host memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(node_memory_MemTotal_bytes{instance=~\"^($Node).*\"} - node_memory_MemFree_bytes{instance=~\"^($Node).*\"} - node_memory_Buffers_bytes{instance=~\"^($Node).*\"} - node_memory_Cached_bytes{instance=~\"^($Node).*\"}) / node_memory_MemTotal_bytes{instance=~\"^($Node).*\"} ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rate(container_cpu_usage_seconds_total{image=~\"($Image)\",instance=~\"^($Node).*\"}[1m])) by (instance, name))",
     "legendFormat": "{{ instance}} {{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(container_memory_usage_bytes{image=~\"($Image)\",instance=~\"^($Node).*\"}) by (instance, name))",
     "legendFormat": "{{ instance}} {{ name }}"
    }
   ]
  },
  {
   "title": "容器内存使用比例",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(container_memory_usage_bytes{image=~\"($Image)\",instance=~\"^($Node).*\"}) by (instance, name) / sum(container_spec_memory_limit_bytes{image=~\"($Image)\",instance=~\"^($Node).*\"}) by (instance, name) * 100)",
     "legendFormat": "{{ instance}} {{ name }}"
    }
   ]
  },
  {
   "title": "容器内存限制",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "container_spec_memory_limit_bytes{image=~\"($Image)\",instance=~\"^($Node).*\"} ",
     "legendFormat": "{{ instance}} {{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (instance,name) (rate(container_network_receive_bytes_total{image=~\"($Image)\",instance=~\"^($Node).*\"}[1m] ) ))",
     "legendFormat": "-> {{ instance }}  {{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (instance, name) (rate(container_network_transmit_bytes_total{image=~\"($Image)\",instance=~\"^($Node).*\"}[1m] ) ))",
     "legendFormat": "<- {{ instance}} {{ name }}"
    }
   ]
  }
 ]
}